### ISSUE TITLE
Do not force to reconnect when going to Home Page

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#111]
Currently the behaviour is that if Im navigating the RIF Marketplace with my wallet CONNECTED and for some reason I want to go to the Home page (for example by clicking on the RIF logo on the top left corner), I get Disconnected and forces me to RECONNECT the Wallet. We should keep the wallet connected the complete session. Once they are connected should remain like that.

**Comment by farinalvaro** [comment]
Solved in `rif-ui` with [this issue](https://github.com/rsksmart/rif-ui/issues/31)
