### ISSUE TITLE
Inform user when no web3 injected

### ISSUE THREAD

**Issue by jurajpiar** [rsksmart/rif-marketplace-ui#132]
Tell user they have no wallet installed.

**Comment by farinalvaro** [comment]
This rimble component could be useful for us as an example: https://rimble.consensys.design/components/web3-components/ConnectionBanner

**Comment by farinalvaro** [comment]
We can probably close this one as we are suggesting to install Nifty when no wallet is detected. What do you guys think? @julianmrodri @jurajpiar

**Comment by julianmrodri** [comment]
Closing as already implemented.
