### ISSUE TITLE
Incomplete UX for blockchain transaction waiting time (RNS purchase).

### ISSUE THREAD

**Issue by jurajpiar** [rsksmart/rif-marketplace-ui#21]
The current idea is that, the UI will wait for the contract to emit the receipt event, upon which it tells the user that the domain in question has been successfully transferred to them, or some such.
This, however is not true yet at this point, as the blockchain has not "validated" this transaction.

We, now should decide how we are going to tackle this. Both from the perspective of the user and in the cache.

**Comment by vojtechsimetka** [comment]
So just to be clear we should only say "Your transaction has been included in the blockchain".

**Comment by vojtechsimetka** [comment]
The next step is then show the confirmations and after x confirmations it will say "Your transaction is now finalized"

**Comment by julianmrodri** [comment]
Cant we just confirm when the transaction is finalized? Telling the user it was included int he blockchain is too technical and detailed, I would prefer to tell the user it is "being processed" until we confirm the transaction is complete.

**Comment by vojtechsimetka** [comment]
Our customers are technical. If they want RNS they know blockchain. But I do agree we can phrase it better.

**Comment by diegomazo12** [comment]
Yes, I think we can phrase it avoiding technical words. Copywriting is a very important part of the experience. Blockchain sometimes is an "empty word meaning wise.

**Comment by julianmrodri** [comment]
We will keep the UX defined in the original User Story. The user will wait for the Transaction confirmation in the same page with the BUY and LIST buttons until the transaction is finalized and confirmed. I.
