### ISSUE TITLE
Read current version from package.json and provide it in the footer

### ISSUE THREAD

**Issue by farinalvaro** [rsksmart/rif-marketplace-ui#212]
This would help to have the footer up to date with the current version of the project

**Comment by julianmrodri** [comment]
Read some concerns about importing the `package.json` because it exposes dependencies which brings security concerns. One option I saw mentioned is to include the Version as a variable in `.env` file. What do you think?

**Comment by julianmrodri** [comment]
I can tackle this once we make a decision on where to retrieve it from.

**Comment by farinalvaro** [comment]
I think we could do just with this:
`import { version } from '../../../package.json'`

**Comment by julianmrodri** [comment]
@jurajpiar what do you think about this? Is this a viable solution? If it is I would suggest to do it. Thanks!

**Comment by jurajpiar** [comment]
Looks like `process.env.npm_package_version` is the safe way to do this. No need to specify it in the .env file
