### ISSUE TITLE
Check `toLowerCase` on available tokens

### ISSUE THREAD

**Issue by farinalvaro** [rsksmart/rif-marketplace-ui#287]
Every time we are calling `availableTokens` we lowerCase the input. It should be better to make it a function that receives the input and lowerCases the input before returning it.

See `src/api/rif-marketplace-cache/rns/common.ts` -> `availableTokens`

**Comment by julianmrodri** [comment]
@farinalvaro @jurajpiar Now that we are tackling lowercasing in the Backend. Maybe is a nice timing to address this. Is it still valid?

**Comment by jurajpiar** [comment]
This is no longer valid @julianmrodri. Thanks for bringing it up
