### ISSUE TITLE
Adapt rns store interfaces

### ISSUE THREAD

**Issue by jurajpiar** [rsksmart/rif-marketplace-ui#310]
- instead of extending StoreState, extend MarketState<T> where T is RnsItem
this abstracts the store structure further

**Comment by julianmrodri** [comment]
@farinalvaro has this been tackled as part of the RNS refactor?

**Comment by farinalvaro** [comment]
@julianmrodri Yes, there might be pending refactors related to contexts/stores but not for RNS
