### ISSUE TITLE
Fix NPM Vulnerabilities

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#33]
Fix vulnerabilities detected with npm audit fix.

**Comment by vojtechsimetka** [comment]
I already added depebdabot which could help us keep the dependencies up to date and hence making it easier for us to be on top of latest dependency security updates.

**Comment by julianmrodri** [comment]
Closing this as we only have some low level vulnerabilites and all from dependences of referenced packages not directly in the dependencies we manage.
