### ISSUE TITLE
Refactor Reducers

### ISSUE THREAD

**Issue by jurajpiar** [rsksmart/rif-marketplace-ui#330]
Refactor RNS and storage offers reducers to reducer per storage bases.

use following file structure:
\\/ contextFolder
- Context.tsx
- actions.ts
- interfaces.ts
- utils.ts
- index.ts

### index.ts
Where all definitions can keep their short, non-domain-specific names even when exported. The items necessary to be accessible from the outside of this namespace should be exported with using their domain-specific designations in the index.ts.

### interfaces.ts
use comments to show logical separation, such as:
```
// STATE
...
// PAYLOAD
...
// ACTIONS
...
```
#### Actions definition
First define Action types. This will force the dispatch call to follow the payload type, also allowing payload itself to be the desired value:
```
export type Action = (
  | {
    type: 'ACTION_TYPE_NAME'
    payload: { property: Type } | Type 
  } ...
)
```
Next, define type for the actions object to follow:
```
export type Actions = {
  ACTION_TYPE_NAME: (
    state: State,
    payload: { property: Type } | Type ,
  ) => State
```

Asynchronous actions should be carried within the context props in an object, sibling to state and dispatch, such as:
```
export type Props = {
    state: State
    dispatch: Dispatch<Action>
    asyncActions: AsyncActions
}
```

Finally, use `src/context/storage/buy/checkout/actions.ts` reducer function as template to try and change the reducer factory so that it doesn't need to be so heavily overtyped.

**Comment by farinalvaro** [comment]
As part of this refactor, we could also move the `isLoading` prop to be handled per service context and not in the `AppContext`.
That way each service would be responsible for handling its own "loading" statement.
