### ISSUE TITLE
Missing price conversion from wei for both price and price filter 

### ISSUE THREAD

**Issue by jurajpiar** [rsksmart/rif-marketplace-ui#376]
<img width="1673" alt="Screenshot 2020-09-29 at 09 06 20" src="https://user-images.githubusercontent.com/36888576/94530483-1131dc00-0233-11eb-92b8-32d518d65110.png">

Expected: price/gb/day and price filter to be in usd
Actual: in wei

**Also to get the data to be displayed I had to comment out the averagePrice in the query.**

Tested with lastest:
- cache: master, multicurrency
- ui: master

**Comment by nduchak** [comment]
Closes: https://github.com/rsksmart/rif-marketplace-cache/pull/303
