### ISSUE TITLE
Extract Staking outside interaction into its Context

### ISSUE THREAD

**Issue by farinalvaro** [rsksmart/rif-marketplace-ui#416]
The functionality that interacts with the outside world and it's not specifically related to the component should be encapsulated in the Staking context.

**Comment by julianmrodri** [comment]
@farinalvaro have you tackled this in the Staking refactor? or this is still pending?

**Comment by farinalvaro** [comment]
@julianmrodri yes, this issue will be obsolete once https://github.com/rsksmart/rif-marketplace-ui/pull/714 is merged

**Comment by julianmrodri** [comment]
Merged into `triggers` branch.
