### ISSUE TITLE
Upgrade logic for new Metamask or implement patch

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#452]
On Nov 16, MetaMask will stop injecting window.web3 and make a limited number of breaking changes to our `window.ethereum` API.  We need to implement the migration guide. There is a workaround patch that can be useful for initial release. (`@metamask/legacy-web3`)

https://docs.metamask.io/guide/provider-migration.html

We have to be careful to keep supporting Nifty wallet if we implement this change.

**Comment by farinalvaro** [comment]
Should be tackled in https://github.com/rsksmart/rif-ui
Just opened this issue https://github.com/rsksmart/rif-ui/issues/184
I think we could keep this issue opened until we integrate that new `rif-ui` version
