### ISSUE TITLE
Validate negative Price/GB and Size field for Offers

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#456]
When creating an Offer with Billing plans it nows allows you to add negative price. And send the transaction.

We should add the validation to avoid negative values, only include values >0.

![image](https://user-images.githubusercontent.com/56316686/98286788-47295500-1f83-11eb-8fc3-067364cf8dd8.png)

Same happens for SIZE:

![image](https://user-images.githubusercontent.com/56316686/98321641-5c72a380-1fc4-11eb-8e2d-c41409df27cb.png)

**Comment by farinalvaro** [comment]
Just for clarification, the user was not able to send the transaction with negative price or size, but was able to move to the next step (`Define plans`) with negative size. That should be fixed by merging #476
