### ISSUE TITLE
Multicurrency Invalid amount in My Purchases  and My Offers when using RIF

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#531]
I created an Agreement in RIF, and in My Purchases I get the current NaN value. We need to make sure we are properly handling agreements created in tokens.

Could be a Cache issue in that case please move to the corresponding Project. 

![image](https://user-images.githubusercontent.com/56316686/100184419-39029080-2ec0-11eb-9866-3ed2a872ef4f.png)

**Comment by julianmrodri** [comment]
Same happens in My Offers, seems this is not prepared to handle multi token.
![image](https://user-images.githubusercontent.com/56316686/100184666-c5ad4e80-2ec0-11eb-9fbf-faa0a81221c8.png)

**Comment by farinalvaro** [comment]
Closed by #551
