### ISSUE TITLE
Renewal returns "Agreement ran out of funds"

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#534]
The renewal functionality does not seem to be working properly. not sure if its UI or contract issue but when creating an agreement and trying to renew I always get "Agreement Run out of funds" which is strange as it is a Monthly plan I just bought. We need to look into this why it is ocurring.

**Comment by farinalvaro** [comment]
Related to https://github.com/rsksmart/rif-marketplace-ui/issues/535. Added the `on hold` label until we check in the `StorageManager` SC if users are able to renew when the current period is the last one

**Comment by julianmrodri** [comment]
This will be fixed with a change in the Storage contract.

**Comment by julianmrodri** [comment]
Closing this as it was address in Storage contract latest release.
