### ISSUE TITLE
Issues after Withdrawing from Agreement

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#535]
Once you withdraw as consumer from an Agreement you cannot renew it and you still have access to the actions of Renew and Withdraw but both fail. We need to define what we do once eveything is withdrawn. Can it be renewed or its a termination of Agreement? If its a termination we have to change the button message and name it accordingly, and disable all future actions.

**Proposed Solution:**  Consider Withdraw as terminated. Do not allow to Renew after that. We may need to rename the button.

**Comment by farinalvaro** [comment]
Closing as it's closely related to #534 and they should be tackled together
