### ISSUE TITLE
Duplicated notifications 

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#593]
We have duplicated confirmations which get based no subscription. After creating an agreement and waiting some period I got doubled notifications (this happened on Staging but once I was able to reproduce locally).

Once you logout and loging again the duplications does not appear, which means the information is properly stored int he table but for some reason gets processed twice in UI.

![image](https://user-images.githubusercontent.com/56316686/101942949-16af8900-3bc9-11eb-859b-6f85e5540a74.png)

**Comment by jurajpiar** [comment]
No longer the case I believe, @julianmrodri?

**Comment by julianmrodri** [comment]
Yes we can close this based on the new notificatino mechanism.
