### ISSUE TITLE
[Storage-Uploader]: Upload files and Pin by hash tabs should be independent

### ISSUE THREAD

**Issue by farinalvaro** [rsksmart/rif-marketplace-ui#661]
## Steps to reproduce
1. Select an offer on Storage/Buy
2. Upload file(s) (on `Upload file` tab)
3. Switch to `Pin by hash` tab
	**ERROR 1**: The size shown is from `step 2` and you are not allowed to check the size of your hash
4. Enter any valid CID, (i.e. `QmTWXNM6o1NnPYGaiwN3he2W56BsGYDufoNnWbjiHY2nfG`)
	**ERROR 2**: By clicking on `Pin` it would upload the content of `step2`, ignoring the hash

**Comment by julianmrodri** [comment]
this is quite important can you tackle it @farinalvaro ?
