### ISSUE TITLE
Compilation error when deploying

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#81]
The project is not running when deployed locally. The following error gets shown ,related to RIF-UI probably.

![image](https://user-images.githubusercontent.com/56316686/81491334-db7c5e80-9263-11ea-985f-38867d453a8b.png)

**Comment by jurajpiar** [comment]
Yes this is indeed a rif-ui issue. Closing and moving it there. [(#17)](https://github.com/rsksmart/rif-ui/issues/17)
