### ISSUE TITLE
Show Hash if Reverse resolution is not set

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#82]
When displaying your domains for sell, if there is no reverse resolution the Hash should be displayed. Now it is leaving empty row.

![image](https://user-images.githubusercontent.com/56316686/81511366-4f177d80-92ef-11ea-86cf-bcab9a9466c1.png)

**Comment by vojtechsimetka** [comment]
We had a discussion about it with @jurajpiar and the conclusion is:

1. We show `Unknown RNS (0x...)` 
2. We extend the search to also look in the tokenId. So the query would have `or tokenId===sha3(search)` which will allow to find a specific RNS name even if marketplace does not know the name.

Under no circumstances will the cache be updated from the UI. The flow will remain unidirectional Blockchain -> Cache -> UI -> Blockchain

**Comment by julianmrodri** [comment]
Sounds good. I agree with the approach.
