### ISSUE TITLE
Styles and format changes

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#83]
1 - For "My Domains" Align titles to the left so they begin where the contents begin:
![image](https://user-images.githubusercontent.com/56316686/81511706-a74f7f00-92f1-11ea-9259-8cf6109990b7.png)

2 -Same happens on the BUY table

![image](https://user-images.githubusercontent.com/56316686/81512204-38742500-92f5-11ea-970c-c1080d4d79cc.png)

3- Show compacted seller Address in the tables. Only the first chars (using same logic we have int he Connect button) , the rest of the address can be displayed as Tooltip.

![image](https://user-images.githubusercontent.com/56316686/81512226-5c376b00-92f5-11ea-9aa2-700df555c1c4.png)

**Comment by jurajpiar** [comment]
No 3 resolved in #79

**Comment by jurajpiar** [comment]
No 1 and 2 fixed in #78 .

**Comment by julianmrodri** [comment]
Looking forward to merging this #78  branchlet me know
