### ISSUE TITLE
Add Application Name and Token to Wallet approval transaction

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#84]
Currently the message we get when we need to approve a transaction in the wallet does not get the App and Domain name correctly. See if we can fix it, in the current example should be:

"Allow RIF MARKETPLACE to spend your "DomainName"?

 ![image](https://user-images.githubusercontent.com/56316686/81511926-25605580-92f3-11ea-877b-9fbba2b55edb.png)

**Comment by jurajpiar** [comment]
Will look into it.

**Comment by vojtechsimetka** [comment]
@jurajpiar This is a good resource https://docs.metamask.io/guide/defining-your-icon.html

**Comment by jurajpiar** [comment]
unassigned myself from this as it's de-prioritised by more pressing issues.

**Comment by julianmrodri** [comment]
No additional action can be taken from the application.
