### ISSUE TITLE
"View Listed domains" not working after Listing

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#86]
Once you list yout own domain and put it for sale you get the confirmation screen with 2 options.

The one "View Listed Domains" does not work, it takes you to the Buy Page but it displays completely empty. You need to refresh to view the info and then you lose your Wallet connection.

**Comment by jurajpiar** [comment]
I believe this is fixed in [pull 79](https://github.com/rsksmart/rif-marketplace-ui/pull/79)
