### ISSUE TITLE
Duplicate Listings

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#87]
If you list your domain multiple times it creates different offers but only the last one should be valid. Now its currently displaying duplicated in all screens (BUY and also mY OFFERS)

![image](https://user-images.githubusercontent.com/56316686/81512574-e4b70b00-92f7-11ea-8f6c-3944034df61c.png)

This is causing another critical issue, for example if you BUY one of the 2 offers, the other remains available. Once you buy a domain it should be taken out of the Marketplace (all offers)

**Comment by jurajpiar** [comment]
This is a cache issue, I think. Please, confirm @leandroyalet @AuHau.

**Comment by jurajpiar** [comment]
This is a cache issue, currently being solved by [PR#72](https://github.com/rsksmart/rif-marketplace-cache/pull/72/files).

**Comment by jurajpiar** [comment]
Moved to cache issue [#74](https://github.com/rsksmart/rif-marketplace-cache/issues/74).
