### ISSUE TITLE
Seeing duplicate Domain after Buying

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-ui#95]
Once you buy a domain and it gets transfered to you it is happening that now I see it twice in the "MyDomains" with the account that just Bough it. the Selled does not see it anymore which it is correct.

![image](https://user-images.githubusercontent.com/56316686/81592892-031f1400-9395-11ea-8b53-0716c947b0b4.png)

Additional info:

* On the Domain_Offer table I see two entrie.s One Canceled and One Sold. (Because I did a republish before) Maybe this is the issue?

Getting this error in console

![image](https://user-images.githubusercontent.com/56316686/81593777-5180e280-9396-11ea-8cc7-6d72291ce6cb.png)

**Comment by jurajpiar** [comment]
Solved in [cache P#90](https://github.com/rsksmart/rif-marketplace-cache/pull/90)
